version: '3'

services:
  
  hafenkran-db:
    image: "postgres:12.0"
    container_name: "hafenkran-db"
    environment:
      - POSTGRES_USER=hafenkran
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=hafenkran
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  hafenkran-userservice:
    container_name: hafenkran-userservice
    build:
      context: ./hafenkran-userservice
      dockerfile: Dockerfile.userservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hafenkran-db:5432/hafenkran
    depends_on:
      - hafenkran-db

  hafenkran-reportingservice:
    container_name: hafenkran-reportingservice
    build:
      context: ./hafenkran-reportingservice
      dockerfile: Dockerfile.reportingservice
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hafenkran-db:5432/hafenkran
    depends_on:
      - hafenkran-db

  hafenkran-proxy:
    container_name: hafenkran-proxy 
    hostname: localhost
    build:
        context: ./hafenkran-proxy
        dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - hafenkran-userservice
      - hafenkran-reportingservice

volumes:
  db-data: {}

