version: '3'

services:
  
  hafenkran-db:
    image: "postgres:12.0"
    container_name: "hafenkran-db"
    environment:
      - POSTGRES_USER=hafenkran
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=hafenkran
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  hafenkran-userservice:
    container_name: hafenkran-userservice
    build:
      context: ./hafenkran-userservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hafenkran-db:5432/hafenkran
    depends_on:
      - hafenkran-db

  hafenkran-clusterservice:
    container_name: hafenkran-clusterservice
    build:
      context: ./hafenkran-clusterservice
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hafenkran-db:5432/hafenkran
    depends_on:
      - hafenkran-db

  hafenkran-client:
    container_name: hafenkran-client
    image: node:alpine
    volumes:
      - ./hafenkran-client:/hafenkran-client
    working_dir: /hafenkran-client
    ports:
      - "8080:8080"
    command: npm start

volumes:
  db-data: {}

